/************************************************************************
 *
 * buttonevent.h
 * ButtonEvent class
 *
  ************************************************************************/

#ifndef BUTTONEVENT_H
#define BUTTONEVENT_H

#include "vector4.h"

/**
 * A ButtonEvent is generated by Application when the user clicks the screen
 * with the mouse. The pointer position is always reported relative to the
 * window and the z coordinate is zero.
 */
class ButtonEvent {
public:
    /**
     * A mouse button.
     */
    enum button {LEFT, MIDDLE, RIGHT};

    /**
     * The state of a button.
     */
    enum bstate {PRESSED, RELEASED};

    /**
     * Constructor.
     *   - b is the button that was pressed or released
     *   - state is the current state of the button
     *   - pos is the position of the pointer when the button was pressed
     *     or released relative to the window
     */
     ButtonEvent(button b, bstate state, vector4 pos);

    /**
     * Copy constructor. The offset is subtracted from the position.
     */
     ButtonEvent(ButtonEvent event, vector4 offset);

    /**
     * Return the button that was pressed or released.
     */
    button getButton();

    /**
     * Return the current state of the button.
     */
    bstate getState();

    /**
     * Return the position of the pointer relative to the window.
     */
    vector4 getPosition();

private:
    /**
     * The button that was clicked.
     */
    button b;

    /**
     * The state of the button.
     */
    bstate state;

    /**
     * The position of the pointer when the button was clicked.
     */
    vector4 pos;
};

#endif //BUTTONEVENT_H

