/************************************************************************
 *
 * keyevent.h
 * KeyEvent class
 *
 ************************************************************************/

#ifndef KEYEVENT_H
#define KEYEVENT_H

/**
 * A KeyEvent is generated by Application when a key is pressed or released.
 */
class KeyEvent {
public:
    /**
     * The state of a key.
     */
    enum kstate {PRESSED, RELEASED};

    /**
     * Constructor.
     *   - key is the key that was pressed or released
     *   - state is the new state of the key
     */
    KeyEvent(char key, kstate state);

    /**
     * Returns the key that was pressed or released.
     */
    char getKey();

    /**
     * Returns the new state of the key.
     */
    kstate getState();

private:
    /**
     * The key that was pressed or released.
     */
    char key;

    /**
     * The new state of the key.
     */
    kstate state;
};

#endif //KEYEVENT_H

