/************************************************************************
 *
 * mouseevent.h
 * MouseEvent class
 *
 ************************************************************************/

#ifndef MOUSEEVENT_H
#define MOUSEEVENT_H

#include "vector4.h"

/**
 * A MouseEvent is generated by Application when a the mouse pointer is moved.
 * The pointer position is always reported relative to the window and the z
 * coordinate is zero.
 */
class MouseEvent {
public:
    /**
     * Constructor.
     *   - pos is the latest pointer position relative to the window
     *   - delta is the change in position since the last event
     */
     MouseEvent(vector4 pos, vector4 delta);

    /**
     * Copy constructor. The offset is subtracted from the position.
     */
     MouseEvent(MouseEvent event, vector4 offset);

    /**
     * Returns the latest pointer position relative to the window.
     */
    vector4 getPosition();

    /**
     * Returns the change in position since the last event.
     */
    vector4 getDelta();

private:
    /**
     * The position of the pointer.
     */
     vector4 pos;
    /**
     * The position of the pointer relative to the last event.
     */
     vector4 delta;
};

#endif //MOUSEEVENT_H

