/************************************************************************
 *
 * mouseevent.cpp
 * MouseEvent class implementation
 *
 ************************************************************************/

#include "mouseevent.h"

/**
 * A MouseEvent is generated by Application when a the mouse pointer is moved.
 * The pointer position is always reported relative to the window and the z
 * coordinate is zero.
 */
MouseEvent::MouseEvent(vector4 pos, vector4 delta)
    : pos(pos), delta(delta)
{
    pos.z = 0;
    delta.z = 0;
}

/**
 * Copy constructor. The offset is subtracted from the position.
 */
MouseEvent::MouseEvent(MouseEvent event, vector4 offset)
{
    pos = event.pos - offset;
    delta = event.delta;

    pos.z = 0;
    delta.z = 0;
}

/**
 * Returns the latest pointer position relative to the window.
 */
vector4 MouseEvent::getPosition()
{
    return pos;
}

/**
 * Returns the change in position since the last event.
 */
vector4 MouseEvent::getDelta()
{
    return delta;
}
